name: Indeed Highlighter ~ Run tests, Build extension, and Deploy to webstore

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Run all tests
        run: npm run test

      - name: Build extension
        run: npx webpack

      - name: Install webstore cli
        run: npm install -g chrome-webstore-upload-cli

      - name: Upload to chrome WebStore
        run: |
          echo "APP_ID: ${{ secrets.APP_ID }}"
          echo "CI_GOOGLE_CLIENT_ID: ${{ secrets.CI_GOOGLE_CLIENT_ID }}"
          echo "CI_GOOGLE_CLIENT_SECRET: ${{ secrets.CI_GOOGLE_CLIENT_SECRET }}"
          echo "CI_GOOGLE_REFRESH_TOKEN: ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}"
          chrome-webstore-upload upload \
            --source extension/extension.zip \
            --extension-id ${{ secrets.APP_ID }} \
            --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} \
            --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} \
            --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }}
      
